git: 
    depth: 2

language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -q $DJANGO
  - python -c "import django;print(django.get_version())"

script:
  - python setup.py test

env:
  - DJANGO=Django==1.11.16
  - DJANGO=Django==2.0.9
  - DJANGO=Django==2.1.2

matrix:
  fast_finish: true
  exclude:
  - python: 2.7
    env: DJANGO=Django==2.0.9
  - python: 2.7
    env: DJANGO=Django==2.1.2
