language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install -q $DJANGO
  - python -c "import django;print(django.get_version())"
  - if [[ $TRAVIS_PYTHON_VERSION = '2.6' ]]; then pip install ordereddict; fi

script:
  - python setup.py test

env:
  - DJANGO=Django==1.4.20
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.11
  - DJANGO=Django==1.7.8
  - DJANGO=Django==1.8.2

matrix:
  fast_finish: true
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7.8
    - python: 2.6
      env: DJANGO=Django==1.8.2
    - python: 3.3
      env: DJANGO=Django==1.4.20
    - python: 3.4
      env: DJANGO=Django==1.4.20
    - python: 3.4
      env: DJANGO=Django==1.5.12
    - python: 3.4
      env: DJANGO=Django==1.6.11
