language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install -q $DJANGO
  - if [[ $TRAVIS_PYTHON_VERSION = '2.6' ]]; then pip install ordereddict; fi
  - python setup.py install

script:
  - python setup.py test

env:
  - DJANGO=Django==1.4
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO="https://www.djangoproject.com/download/1.7c2/tarball/"
  - DJANGO="git+git://github.com/django/django.git@master#egg=django"
 
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/download/1.7c2/tarball/"
