language: python
python:
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install -q $DJANGO
  - python -c "import django;print(django.get_version())"

script:
  - python setup.py test

env:
  - DJANGO=Django==1.7.8
  - DJANGO=Django==1.8.4

matrix:
  fast_finish: true
