language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install -q $DJANGO
  - pip install tox
  - python setup.py install

script:
  - tox

env:
  - DJANGO=Django==1.4
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO="https://www.djangoproject.com/download/1.7c2/tarball/"
  - DJANGO="git+git://github.com/django/django.git@master#egg=django"
